BEGIN TRANSACTION;
CREATE TABLE citacao (_id INTEGER PRIMARY KEY, frase TEXT);
INSERT INTO citacao VALUES(1,'O que eu faço não o sabes tu agora, mas tu o saberás depois. João 13:7 ');
INSERT INTO citacao VALUES(2,'Bem-aventurados sois vós, quando vos injuriarem e perseguirem e, mentindo, disserem todo o mal contra vós por minha causa. Exultai e alegrai-vos, porque é grande o vosso galardão nos céus; porque assim perseguiram os profetas que foram antes de vós. Mateus 5:11-12');
INSERT INTO citacao VALUES(3,'Vós sois o sal da terra; e se o sal for insípido, com que se há de salgar? Para nada mais presta senão para se lançar fora, e ser pisado pelos homens. Mateus 5:13');
INSERT INTO citacao VALUES(4,'Porque em verdade vos digo que, até que o céu e a terra passem, nem um jota ou um til se omitirá da lei, sem que tudo seja cumprido. Mateus 5:18');
INSERT INTO citacao VALUES(5,'Ouvistes que foi dito aos antigos: Não matarás; mas qualquer que matar será réu de juízo. Eu, porém, vos digo que qualquer que, sem motivo, se encolerizar contra seu irmão, será réu de juízo; e qualquer que disser a seu irmão: Raca, será réu do sinédrio; e qualquer que lhe disser: Louco, será réu do fogo do inferno. Mateus 5:21-22');
INSERT INTO citacao VALUES(6,'Seja, porém, o vosso falar: Sim, sim; Não, não; porque o que passa disto é de procedência maligna. Mateus 5:37');
INSERT INTO citacao VALUES(7,'Ouvistes que foi dito: Olho por olho, e dente por dente. Eu, porém, vos digo que não resistais ao mal; mas, se qualquer te bater na face direita, oferece-lhe também a outra; E, ao que quiser pleitear contigo, e tirar-te a túnica, larga-lhe também a capa; E, se qualquer te obrigar a caminhar uma milha, vai com ele duas. Mateus 5:38-41');
INSERT INTO citacao VALUES(8,'Venha o teu reino, seja feita a tua vontade, assim na terra como no céu; Mateus 6:10');
INSERT INTO citacao VALUES(9,'A candeia do corpo são os olhos; de sorte que, se os teus olhos forem bons, todo o teu corpo terá luz; Se, porém, os teus olhos forem maus, o teu corpo será tenebroso. Se, portanto, a luz que em ti há são trevas, quão grandes serão tais trevas!  Mateus 6:22-23');
INSERT INTO citacao VALUES(10,'Por isso vos digo: Não andeis cuidadosos quanto à vossa vida, pelo que haveis de comer ou pelo que haveis de beber; nem quanto ao vosso corpo, pelo que haveis de vestir. Não é a vida mais do que o mantimento, e o corpo mais do que o vestuário? Mateus 6:25');
INSERT INTO citacao VALUES(11,'Mas, buscai primeiro o reino de Deus, e a sua justiça, e todas estas coisas vos serão acrescentadas.  Mateus 6:33');
INSERT INTO citacao VALUES(12,'Não vos inquieteis, pois, pelo dia amanhã, porque o dia de amanhã cuidará de si mesmo. Basta a cada dia o seu mal. Mateus 6:34');
INSERT INTO citacao VALUES(13,'Não julgueis, para que não sejais julgados. Porque com o juízo com que julgardes sereis julgados, e com a medida com que tiverdes medido vos hão de medir a vós. Mateus 7:1-2');
INSERT INTO citacao VALUES(14,'Não deis aos cães as coisas santas, nem deiteis aos porcos as vossas pérolas, não aconteça que as pisem com os pés e, voltando-se, vos despedacem.  Mateus 7:6');
INSERT INTO citacao VALUES(15,'Portanto, tudo o que vós quereis que os homens vos façam, fazei-lho também vós, porque esta é a lei e os profetas.  Mateus 7:12');
INSERT INTO citacao VALUES(16,'Entrai pela porta estreita; porque larga é a porta, e espaçoso o caminho que conduz à perdição, e muitos são os que entram por ela; E porque estreita é a porta, e apertado o caminho que leva à vida, e poucos há que a encontrem. Mateus 7:13-14');
INSERT INTO citacao VALUES(17,'Nem todo o que me diz: Senhor, Senhor! entrará no reino dos céus, mas aquele que faz a vontade de meu Pai, que está nos céus. Mateus 7:21');
INSERT INTO citacao VALUES(18,'Vai, e como creste te seja feito. E naquela mesma hora o seu criado sarou. Mateus 8:13');
INSERT INTO citacao VALUES(19,'Segue-me, e deixa os mortos sepultar os seus mortos. Mateus 8:22');
INSERT INTO citacao VALUES(20,'Ouvistes que foi dito: Amarás o teu próximo, e odiarás o teu inimigo. Eu, porém, vos digo: Amai a vossos inimigos, bendizei os que vos maldizem, fazei bem aos que vos odeiam, e orai pelos que vos maltratam e vos perseguem; para que sejais filhos do vosso Pai que está nos céus; Porque faz que o seu sol se levante sobre maus e bons, e a chuva desça sobre justos e injustos. Pois, se amardes os que vos amam, que galardão tereis? Não fazem os publicanos também o mesmo?  Mateus 5:43-46');
INSERT INTO citacao VALUES(21,'Mas tu, quando orares, entra no teu aposento e, fechando a tua porta, ora a teu Pai que está em secreto; e teu Pai, que vê em secreto, te recompensará publicamente. E, orando, não useis de vãs repetições, como os gentios, que pensam que por muito falarem serão ouvidos. Não vos assemelheis, pois, a eles; porque vosso Pai sabe o que vos é necessário, antes de vós lho pedirdes.  Mateus 6:6-8');
INSERT INTO citacao VALUES(22,'Por que temeis, homens de pouca fé? Então, levantando-se, repreendeu os ventos e o mar, e seguiu-se uma grande bonança. Mateus 8:26');
INSERT INTO citacao VALUES(23,'Filho, tem bom ânimo, perdoados te são os teus pecados.  Mateus 9:2');
INSERT INTO citacao VALUES(24,'Em verdade, em verdade vos digo que eu sou a porta das ovelhas. Todos quantos vieram antes de mim são ladrões e salteadores; mas as ovelhas não os ouviram. Eu sou a porta; se alguém entrar por mim, salvar-se-á, e entrará, e sairá, e achará pastagens. João 10:7-9');
INSERT INTO citacao VALUES(25,'Não necessitam de médico os sãos, mas, sim, os doentes.  Mateus 9:12');
INSERT INTO citacao VALUES(26,'Podem porventura andar tristes os filhos das bodas, enquanto o esposo está com eles? Dias, porém, virão, em que lhes será tirado o esposo, e então jejuarão. Mateus 9:15');
INSERT INTO citacao VALUES(27,'A seara é realmente grande, mas poucos os ceifeiros. Mateus 9:37');
INSERT INTO citacao VALUES(28,'Se eu quero que ele fique até que eu venha, que te importa a ti? Segue-me tu. João 21:22');
INSERT INTO citacao VALUES(29,'É chegado o reino dos céus. Mateus 10:7');
INSERT INTO citacao VALUES(30,'Mulher, por que choras? João 20:13');
INSERT INTO citacao VALUES(31,'Curai os enfermos, limpai os leprosos, ressuscitai os mortos, expulsai os demônios; de graça recebestes, de graça dai. Mateus 10:8');
INSERT INTO citacao VALUES(32,'Nem alforjes para o caminho, nem duas túnicas, nem alparcas, nem bordão; porque digno é o operário do seu alimento. Mateus 10:10');
INSERT INTO citacao VALUES(33,'E, se a casa for digna, desça sobre ela a vossa paz; mas, se não for digna, torne para vós a vossa paz.  Mateus 10:13');
INSERT INTO citacao VALUES(34,'Mas, quando vos entregarem, não vos dê cuidado como, ou o que haveis de falar, porque naquela mesma hora vos será ministrado o que haveis de dizer. Mateus 10:19');
INSERT INTO citacao VALUES(35,'E odiados de todos sereis por causa do meu nome; mas aquele que perseverar até ao fim será salvo. Mateus 10:22');
INSERT INTO citacao VALUES(36,'Basta ao discípulo ser como seu mestre, e ao servo como seu senhor. Se chamaram Belzebu ao pai de família, quanto mais aos seus domésticos? Mateus 10:25');
INSERT INTO citacao VALUES(37,'E não temais os que matam o corpo e não podem matar a alma; temei antes aquele que pode fazer perecer no inferno a alma e o corpo. Mateus 10:28');
INSERT INTO citacao VALUES(38,'Portanto, qualquer que me confessar diante dos homens, eu o confessarei diante de meu Pai, que está nos céus. Mas qualquer que me negar diante dos homens, eu o negarei também diante de meu Pai, que está nos céus.  Mateus 10:32-33');
INSERT INTO citacao VALUES(39,'E assim os inimigos do homem serão os seus familiares.  Mateus 10:36');
INSERT INTO citacao VALUES(40,'E quem não toma a sua cruz, e não segue após mim, não é digno de mim. Mateus 10:38');
INSERT INTO citacao VALUES(41,'E qualquer que tiver dado só que seja um copo de água fria a um destes pequenos, em nome de discípulo, em verdade vos digo que de modo algum perderá o seu galardão.  Mateus 10:42');
INSERT INTO citacao VALUES(42,'Em verdade vos digo que, entre os que de mulher têm nascido, não apareceu alguém maior do que João o Batista; mas aquele que é o menor no reino dos céus é maior do que ele.  Mateus 11:11');
INSERT INTO citacao VALUES(43,'Vinde a mim, todos os que estais cansados e oprimidos, e eu vos aliviarei. Tomai sobre vós o meu jugo, e aprendei de mim, que sou manso e humilde de coração; e encontrareis descanso para as vossas almas. Porque o meu jugo é suave e o meu fardo é leve.  Mateus 11:28-30');
INSERT INTO citacao VALUES(44,'Pois eu vos digo que está aqui quem é maior do que o templo. Mateus 12:6');
INSERT INTO citacao VALUES(45,'Quem não é comigo é contra mim; e quem comigo não ajunta, espalha. Mateus 12:30');
INSERT INTO citacao VALUES(46,'Granjeai amigos com as riquezas da injustiça; para que, quando estas vos faltarem, vos recebam eles nos tabernáculos eternos.  Lucas 16:9');
INSERT INTO citacao VALUES(47,'Olhai por vós mesmos. E, se teu irmão pecar contra ti, repreende-o e, se ele se arrepender, perdoa-lhe. E, se pecar contra ti sete vezes no dia, e sete vezes no dia vier ter contigo, dizendo: Arrependo-me; perdoa-lhe. Lucas 17:3-4');
INSERT INTO citacao VALUES(48,'Levanta-te, e vai; a tua fé te salvou. Lucas 17:19');
INSERT INTO citacao VALUES(49,'Todavia digo-vos a verdade, que vos convém que eu vá; porque, se eu não for, o Consolador não virá a vós; mas, quando eu for, vo-lo enviarei. João 16:7');
INSERT INTO citacao VALUES(50,'Tirai a pedra.  João 11:39');
INSERT INTO citacao VALUES(51,'Não te hei dito que, se creres, verás a glória de Deus? João 11:40');
INSERT INTO citacao VALUES(52,'A luz ainda está convosco por um pouco de tempo. Andai enquanto tendes luz, para que as trevas não vos apanhem; pois quem anda nas trevas não sabe para onde vai. João 12:35');
INSERT INTO citacao VALUES(53,'E se alguém ouvir as minhas palavras, e não crer, eu não o julgo; porque eu vim, não para julgar o mundo, mas para salvar o mundo. João 12:47');
COMMIT;